server:
  port: 8088
spring:
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=nfhis
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html
    suffix: .flt
    check-template-location: true
    template-loader-path: classpath:/templates
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    request-context-attribute: request
  mvc:
    static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.hospital.entity
  http:
    multipart:
      maxFileSize: 500Mb
      maxRequestSize: 500Mb
filepath:
  appointpdf: D:\\
  seekpdfpath: D:\\